### ISSUE TITLE
Mac has two bugs

### ISSUE THREAD

**Issue by peterremote1980** [sfatihk/electron-tray-window#1]
Hi
   Mac has two bugs
1. clicking the tray icon very fast, it crash
2. click the close button of the window, then click the tray icon, it crash too

```
	const trayWindow = require("electron-tray-window");
	tray = new Tray('image/sharepoint2019.png')
	window = new BrowserWindow({
		width: 800,
		height: 600
	});
	window.loadFile('index.html')
	trayWindow.setOptions({
		tray: tray,
		window: window
	});
```

thanks
Peter

**Comment by sfatihk** [comment]
Hi Peter, 
I fixed that issue, you can check d9ee608.

Now when click the close button of the window, just it will hide.

Thanks you for contributions
