### ISSUE TITLE
app.quit() not working

### ISSUE THREAD

**Issue by quantrpeter** [sfatihk/electron-tray-window#4]
Hi all
    app.quit() not working, i double checked it has ran, but just can't stop the app. Please help and thanks
Peter

```
const menu = new Menu();
		menu.append(new MenuItem({
			label: "Exit", click() {
				app.quit();
			}
		}));
		tray.setContextMenu(menu);
```

**Comment by kierancrowntrt** [comment]
I tried to create a pull request but couldn't figure it out so I create a workaround as seen [here](https://github.com/kierancrown/electron-tray-manager)

**Comment by blahmonkey** [comment]
app.exit(0) works fine, if anybody needs

**Comment by sfatihk** [comment]
thanks, @blahmonkey.
So, I can close this issue.
