### ISSUE TITLE
Can see black border run on Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by ycrao** [sfatihk/electron-tray-window#6]
Can see black border run on Ubuntu 16.04 LTS

`transparent:true` do not seem to work. Is that electron bug?

![image](https://user-images.githubusercontent.com/3280204/100302777-0480f880-2fd6-11eb-89a1-58d07c99fd57.png)

**Comment by ycrao** [comment]
I opened a pull request to fix this. ref link: https://stackoverflow.com/questions/53538215/cant-succeed-in-making-transparent-window-in-electron-javascript/53612021#53612021

**Comment by sfatihk** [comment]
I thank you for you see the issue and fix 🎉🎉 @ycrao
have a nice days
